#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/indel.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/coxy-code;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
