#!/usr/bin/env bash
# customizing 404 page

apt-get update
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/indel.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/coxy-code;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#creating a 404 error page

echo "this is not the page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html;{\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s|listen 80 default_server;|$string_for_replacement|" /etc/nginx/sites-enabled/default

#restart nginx after implementing changes

sudo service nginx restart
