#!/usr/bin/env bash
#configure Nginx so that its HTTP response contains a custom header
# HTTP response contains a custom header (on web-01 and web-02)

# Updating packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a redirection
new_string=server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/coxy-code permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating custom error page
echo "This is not the page" | sudo tee /var/www/html/404.html

# Custom HTTP response
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for errors
sudo nginx -t

# Restart nginx 
sudo service nginx restart
